import type { Metadata } from "next";
import { Affix } from "@kadoui/react";
import { Geist } from "next/font/google";
import { PropsWithChildren } from "react";
import { ArrowUpIcon } from "lucide-react";
import { ThemeAdapter } from "@kadoui/next";

import "./globals.css";
import Header from "root/components/static/Header/Header";
import Footer from "root/components/static/Footer/Footer";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en" className={geist.variable} suppressHydrationWarning>
      <head>
        <ThemeAdapter />
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body>
        <Header />
        {children}
        <Footer />

        <Affix className="ltr:affix-br rtl:affix-bl btn btn-fill btn-square group not-[.affix-active]:scale-90">
          <ArrowUpIcon className="btn-icon-size transition-transform duration-300 group-not-[.affix-active]:translate-y-full" />
        </Affix>
      </body>
    </html>
  );
};

export default RootLayout;
