import type { Metadata } from "next";
import { PropsWithChildren } from "react";

import "./globals.css";
import Header from "root/components/templates/Header/Header";
import Footer from "root/components/templates/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="transition-transform duration-500" id="root">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
